// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBidgQbjQsZvKyTATHM_v9g-fq_nqD6lM',
    appId: '1:202635662089:web:6c59b7144bd3acac4279d8',
    messagingSenderId: '202635662089',
    projectId: 'binary-brigade-get-fit',
    authDomain: 'binary-brigade-get-fit.firebaseapp.com',
    storageBucket: 'binary-brigade-get-fit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrFIE3Z6ShEByHM6myCSI_PH_HGUvWNMs',
    appId: '1:202635662089:android:904c67d1261467df4279d8',
    messagingSenderId: '202635662089',
    projectId: 'binary-brigade-get-fit',
    storageBucket: 'binary-brigade-get-fit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKb50_iL-r-TC-VJLg7CbzljPVs9d9hTw',
    appId: '1:202635662089:ios:cc963fb49581268f4279d8',
    messagingSenderId: '202635662089',
    projectId: 'binary-brigade-get-fit',
    storageBucket: 'binary-brigade-get-fit.appspot.com',
    iosBundleId: 'com.example.binarybrigade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKb50_iL-r-TC-VJLg7CbzljPVs9d9hTw',
    appId: '1:202635662089:ios:99500f698b7c389d4279d8',
    messagingSenderId: '202635662089',
    projectId: 'binary-brigade-get-fit',
    storageBucket: 'binary-brigade-get-fit.appspot.com',
    iosBundleId: 'com.example.binarybrigade.RunnerTests',
  );
}
